### ISSUE TITLE
publicPath still doesn't work

### ISSUE THREAD

**Issue by Erichain** [lili21/critical-css-webpack-plugin#1]
My webpack's output configuration has a publicPath config, and the plugin's config in my project is shown below:

``` javascript
new HtmlCriticalPlugin({
  base: path.resolve(__dirname, 'dist'),
  src: 'index.html',
  dest: 'index.html',
  inline: true,
  minify: true,
  extract: true,
  penthouse: {
    blockJSRequests: false,
  },
})
```

After building with a publicPath config, I cannot find any css file extracted from this plugin in `dist` ditectory, but when I remove publicPath config and build again, the css file appears.

**Comment by lili21** [comment]
Please provide full webpack config or a reproduce repo.

**Comment by Erichain** [comment]
https://github.com/Erichain/critical-css-plugin-demo

I created a demo project to reproduce this problem.

But since the `publicPath` I used is just for internal use only, so I'm sorry I cannot provide it to you.

When you run `npm run build` without a publicPath config, you should see two css files in the `dist/css` directory. But if you add a publicPath config except `{ public: '/' }` and run building, you should see there is only one css file which is extracted by `extract-text-plugin`, not by the `critical-css-webpack-plugin`.

**Comment by lili21** [comment]
You're using wrong plugin. **critical-css-webpack-plugin** instead of **html-critical-webpack-plugin**

**Comment by Erichain** [comment]
Sorry, wrongly written. But the problem still remains with `critical-css-webpack-plugin`.
